### PR TITLE
Fix #86 by fixing non-rpc request and response marshalling regression

### LINKED ISSUE #86: Non RPC function not able to be xml encoded properly
After #75, the generated file contains request that cannot be properly XML encoded.

For example, see https://play.golang.org/p/1aVTcYXYb2j (which is derived from https://raw.githubusercontent.com/fiorix/wsdl2go/master/wsdlgo/testdata/data.golden) - the request cannot be XML encoded.

### PR DESCRIPTION
**Pull request by Kernle32DLL**
I don't know why I didn't see this when I was developing #75, and I'm terrible sorry for breaking this.

`xml:"-"` will cause the struct field to be dropped instead of inlined. The key is to either use composition (for non-rpc) or a field (for rpc). Note when looking at the golden files how some requests start with `M ....` (rpc), and some don't (non-rpc).

The xml tag is now always set, as it is ignored when using composition anyway (however - important as to not drop the object).

One can play around [with this](https://play.golang.org/p/KmxJK_YpL2o) (use locally, does not work in playground due to import). Look at line 121, and experiment with prefixing M to see how the xml request changes for rpc. Setting the xml in either line 121 or 129 to "-" (as was done prior to this PR), you will run into errors (wrong request marshalling, and panic for the response).

### CODE REVIEW

File: wsdlgo/encoder.go [hunk 1]
```diff
@@ -682,21 +682,16 @@ func (ge *goEncoder) writeSOAPFunc(w io.Writer, d *wsdl.Definitions, op *wsdl.Op
...
-		opResponseName = fmt.Sprintf("%sResponse", op.Name)
+	// Check if we need to prefix the op with a namespace
+	namespacedOpName := op.Name
+	nsSplit := strings.Split(ge.funcs[op.Name].Input.Message, ":")
+	if len(nsSplit) > 1 {
+		namespacedOpName = nsSplit[0] + ":" + namespacedOpName
 	}
 
+	// The response name is always the operation name + "Response" according to specification
+	opResponseName := fmt.Sprintf("%sResponse", op.Name)
```
Comment (fiorix) [inline wsdlgo/encoder.go]: not nitpicking but this could be just `op.Name + "Response"` since it needs no formatting.

Comment (Kernle32DLL) [reply wsdlgo/encoder.go]: Agreed

**Comment by fiorix** [comment]
Tests were failing for Go 1.7 because of some network problem in Travis. Just restarted the tests and once it pass I'll rebase and merge.
